name: EOS EVM Contract CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  documentation:
    name: Attach Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'false'

      - name: Attach Documentation
        run: cat .github/workflows/contract.md >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        DWITH_TEST_ACTIONS: ['off']
    name: EOS EVM Contract Build - Tests ${{ matrix.DWITH_TEST_ACTIONS }}
    env:
      DCMAKE_BUILD_TYPE: 'Release'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Download CDT
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: AntelopeIO
          repo: cdt
          target: 'v3.1.0'
          prereleases: false
          file: 'cdt_.*amd64.deb'

      - name: Install CDT
        run: sudo apt-get install -y ./cdt*.deb

      - name: Build EOS EVM Contract
        run: .github/workflows/build-contract.sh
        env:
          DWITH_TEST_ACTIONS: ${{ matrix.DWITH_TEST_ACTIONS }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract.test-actions-${{ matrix.DWITH_TEST_ACTIONS }}.tar.gz
          path: contract.tar.gz
          if-no-files-found: error

      - name: Download Leap - dev binary
        uses: AntelopeIO/asset-artifact-download-action@v3
        with:
          owner: AntelopeIO
          repo: leap
          target: '^5.0.1'
          prereleases: false
          file: 'leap-dev.*ubuntu22\.04_amd64.deb'
          container-package: experimental-binaries
          artifact-name: leap-dev-ubuntu22-amd64

      - name: Install Leap
        run: sudo apt-get install -y ./leap*.deb

      - name: Build EOS EVM Contract Tests
        run: .github/workflows/build-contract-test.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract-test.tar.gz
          path: contract-test.tar.gz
          if-no-files-found: error

      - name: Test EOS EVM Contract
        run: .github/workflows/test-contract.sh
        env:
          DWITH_TEST_ACTIONS: ${{ matrix.DWITH_TEST_ACTIONS }}

      - name: Upload Test Metrics
        uses: actions/upload-artifact@v3
        with:
          name: test-results.xml
          path: test-results.xml
          if-no-files-found: error
